
def template(model, mode, obj, batch, gtype, hidden, domain, dataset, 
        percent, seed, vecfile='None',gamma='5.0',lr='0.1',lr_divide='2',
        topk='5',overgen='20',beamwidth='10',decode='beam'):
    
    text = '[learn] // parameters for training\n'
    text+= 'lr = '+lr+'\n'
    text+= 'lr_decay = 0.5\n'
    text+= 'lr_divide= '+lr_divide+'\n'
    text+= 'beta = 0.0000001\n'
    text+= 'random_seed = '+seed+'\n'
    text+= 'min_impr = 1.003\n'
    text+= 'debug = True\n'
    text+= 'llogp = -100000000\n'
    text+= '\n'
    text+= '[train_mode]\n'
    text+= 'mode        = '+mode+'\n'
    text+= 'obj         = '+obj+'\n'
    text+= 'gamma       = '+gamma+'\n'
    text+= 'batch       = '+batch+'\n'
    text+= '\n'
    text+= '[generator] // structure for generator\n'
    text+= 'type        = '+gtype+'\n'
    text+= 'hidden      = '+hidden+'\n\n'
    text+= '\n'
    text+= '[data] // data and model file\n'
    text+= 'domain      = '+domain+'\n'
    text+= 'train       = data/'+dataset+'/train.json\n'
    text+= 'valid       = data/'+dataset+'/valid.json\n'
    text+= 'test        = data/'+dataset+'/test.json\n'
    text+= 'vocab       = resource/vocab\n'
    text+= 'percentage  = '+percent+'\n'
    text+= 'wvec        = '+vecfile+'\n'
    text+= 'model       = '+model+'\n'
    text+= '\n'
    text+= '[gen] // generation parameters\n'
    text+= 'topk        = '+topk+'\n'
    text+= 'overgen     = '+overgen+'\n'
    text+= 'beamwidth   = '+beamwidth+'\n'
    text+= 'detectpairs = resource/detect.pair\n'
    text+= 'verbose     = 1\n'
    text+= 'decode      = '+decode+'\n'
    text+= '\n'
    return text

